Feature/#16
f-lab-edu/todo-list pull request #17
Opened 2023-01-22 18:10 UTC by gimseonjin

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature

## What is the current behavior?

Issue Number: #16 

## What is the new behavior?

## PR information

1. DB 세팅을 했습니다.
  1-1. create_table.sql에 todo 생성하는 sql문을 추가했습니다.
  1-2. mybatis-mapper 폴더 하위에 mybatis 설정 xml 파일을 추가했습니다.
3. global exception 세팅을 했습니다.
  2-1. common 폴더 하위에 exception 폴더에 관련 세팅을 하였습니다.
5. todo 조회에 필요한 controller & service & repository & test를 구현했습니다.

2023-01-22 18:17 UTC, gimseonjin commented
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[TodoController.java](https://github.com/f-lab-edu/todo-list/blob/38ffe07bc815116755e4fdcd034ca0938a00ac16/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoController.java)|100%|:green_apple:|
|[TodoService.java](https://github.com/f-lab-edu/todo-list/blob/38ffe07bc815116755e4fdcd034ca0938a00ac16/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoService.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

2023-01-22 18:29 UTC, gimseonjin commented
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[TodoController.java](https://github.com/f-lab-edu/todo-list/blob/d499695ffa4cb8012304881a17d466f9cef5faca/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoController.java)|100%|:green_apple:|
|[TodoService.java](https://github.com/f-lab-edu/todo-list/blob/d499695ffa4cb8012304881a17d466f9cef5faca/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoService.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

2023-01-23 14:12 UTC, kyucumber requested changes

2023-01-23 14:12 UTC, kyucumber commented on src/main/java/com/flab/todo/common/exception/RestApiException.java
> +public class RestApiException {
이건 Exception이 아니라 Error 등의 상황에 응답하기 위한 클래스로 보입니다.

Exception이란 네이밍이 아니라 ErrorResponse 등의 이름이 적절하지 않을까요?

2023-01-23 14:12 UTC, kyucumber commented on src/main/java/com/flab/todo/common/exception/ErrorCode.java
> +	private final String message;
중요한 부분은 아닌데 RestApiException와 일관성이 없네요

여긴 status가 int고 저긴 HttpStatus 그리고 여긴 message 저긴 msg로 사용되고 있어서 일관성이 맞춰지면 좋을 것 같습니다.

2023-01-23 14:12 UTC, kyucumber commented on src/main/java/com/flab/todo/common/exception/RestApiException.java
> +	private String code;
이 애플리케이션 내부에서 에러 응답에 사용할 code기 때문에 enum을 타입으로 두는게 좋을 것 같아요. 오타 등으로 존재하지 않는 에러 코드를 응답하게 되면 클라이언트에서 처리할 수 없을 수도 있으니까요.
enum을 타입으로 두면 자연스러울 것 같은데 ErrorCode enum이 code뿐만 아니라 메세지와 status를 가지고 있어서 고민이 조금 필요할 것 같습니다.

2023-01-23 14:20 UTC, jaeyeonme commented on src/main/java/com/flab/todo/common/dto/RequestTodoListDto.java
> +public class RequestTodoListDto {
그렇다면 DTO 라는 명칭을 꼭 쓰고 싶다면 TodoListDTO 로 하거나 RequestTodoList 로 하는편이 좋다는 말씀이시죠?!

2023-01-23 14:23 UTC, gimseonjin commented on .github/workflows/build.yml
>    pull_request:
@jaeyeonme 

feature/#PR_number-PR_title

ex)feature/#16-todo-생성

2023-01-23 14:25 UTC, gimseonjin commented on src/main/java/com/flab/todo/common/dto/RequestTodoListDto.java
> +public class RequestTodoListDto {
@jaeyeonme 

DTO라는 워딩을 사용하지 않고 Request~~ || Response~~ 로 사용하기

2023-01-23 14:31 UTC, gimseonjin commented on src/test/java/com/flab/todo/todo/TodoServiceTest.java
> +		when(todoRepository.findByUserId(1L)).thenReturn(result);
@jaeyeonme 

TDD : 테스트 케이스 기반의 프로그래밍 방법
BDD : 사용자 시나리오 기반의 프로그래밍 방법

둘의 가장 큰 차이는 BDD가 조금 더 고수준의 테스트 케이스를 작성하는 듯 하다.(사람이 읽기 더 쉬운 테스트 케이스)

조금 더 공부해볼 필요가 있으나 확실히 지금 케이스에서는 given 자리에 when 들어가는 것 보다 훨 가독성이 높다!!

BDDMockito를 사용하자!!

2023-01-23 14:35 UTC, gimseonjin commented on src/main/java/com/flab/todo/common/exception/CustomException.java
> +public class CustomException extends RuntimeException {
@jaeyeonme 

표준 예외를 사용합시다!

<img width="750" alt="image" src="https://user-images.githubusercontent.com/66009926/214065632-96e12bd6-cb65-4be4-a6f0-8a272a9719ab.png">

2023-01-23 14:39 UTC, kyucumber commented on src/main/java/com/flab/todo/common/dto/RequestTodoListDto.java
> +public class RequestTodoListDto {
엇 아뇨 그냥 TodoCreateRequest 요런식으로 쓰는걸 선호하긴 해요.

Dto가 올바른 영어 단어가 아니라 문법 오류가 체크되는 부분이 별로라서 선호하지 않아요.
근데 이건 개인 취향이라서요 참고만 하시고 Dto로 쓰셔도 됩니다. DTO는 카멜케이스가 아니라 오히려 이상한것 같아요.

2023-01-23 15:29 UTC, gimseonjin commented
|File|Coverage [100%]|:green_apple:|
|:-|:-:|:-:|
|[TodoController.java](https://github.com/f-lab-edu/todo-list/blob/e68dcb768610336068b7adba761dece99ce3b174/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoController.java)|100%|:green_apple:|
|[TodoService.java](https://github.com/f-lab-edu/todo-list/blob/e68dcb768610336068b7adba761dece99ce3b174/src%2Fmain%2Fjava%2Fcom%2Fflab%2Ftodo%2Ftodo%2FTodoService.java)|100%|:green_apple:|

|Total Project Coverage|100%|:green_apple:|
|:-|:-:|:-:|

2023-01-29 14:01 UTC, closed without merging