Feature/#18
f-lab-edu/todo-list pull request #32
Opened 2023-02-08 12:08 UTC by jaeyeonme

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [O] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [O] Feature

## What is the current behavior?

Issue Number: #18 

## What is the new behavior?

## PR information
1. 이메일로 회원가입을 하면 해당 인증코드를 같이 보낸다.
- 이메일 검증은 이메일로 검증 코드를 보내고 유저는 이를 입력해야만 회원가입이 완료된다.
- 이메일 검증에 사용되는 이메일은 아이디로 사용될 이메일이다.

2. 회원가입할 때, email 중복 체크를 한다.
- 중복이면 다른 이메일를 입력하도록 한다.

3.비밀번호에 특수기호 & 8자리 이상으로 제한한다.
- 서버에 들어올 때, 위 조건을 한 번 더 체크한다.

2023-02-08 12:17 UTC, gimseonjin commented on src/main/java/com/flab/todo/common/config/MailConfig.java
> +	public JavaMailSender javaMailService() {
저는 개인적으로 @Bean 으로 하는 것보다 @Service로 해서 별도의 MailService로 만드는 게 더 좋을 거 같아요!!

MailSerivce가 Config보다 더 상위 계층 같아서요

2023-02-08 12:18 UTC, gimseonjin commented on src/main/java/com/flab/todo/member/MemberController.java
> +		if (errors.hasErrors()) {
여기 errors에 잡히는 에러는 뭐가 있나요??

2023-02-08 12:19 UTC, gimseonjin commented on src/main/java/com/flab/todo/member/MemberService.java
> +	@Transactional
얘 Transactional 없어도 되지 않을까요???

2023-02-09 11:21 UTC, f-lab-kyucumber requested changes

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/common/config/SecurityConfig.java
> +	}
이전에 잠시 같이 얘기했던 것 같은데요. 시큐리티가 필요 없고 BCryptPasswordEncoder만 필요하다고 말씀하셨던 것 같아요. 저거만 단독으로 쓸 수 있는지는 확인해보진 않았지만 의존성을 살펴보시고 가능하다면 필요한 의존성만 주입받으시는게 좋습니다.

```java
package org.springframework.security.crypto.bcrypt;

import java.security.SecureRandom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Implementation of PasswordEncoder that uses the BCrypt strong hashing function. Clients
 * can optionally supply a "version" ($2a, $2b, $2y) and a "strength" (a.k.a. log rounds
 * in BCrypt) and a SecureRandom instance. The larger the strength parameter the more work
 * will have to be done (exponentially) to hash the passwords. The default value is 10.
 *
 * @author Dave Syer
 */
public class BCryptPasswordEncoder implements PasswordEncoder {
```


```
./gradlew dependencies

+--- org.springframework.boot:spring-boot-starter-security -> 2.7.7
|    +--- org.springframework.boot:spring-boot-starter:2.7.7 (*)
|    +--- org.springframework:spring-aop:5.3.24 (*)
|    +--- org.springframework.security:spring-security-config:5.7.6
|    |    +--- org.springframework.security:spring-security-core:5.7.6
|    |    |    +--- org.springframework.security:spring-security-crypto:5.7.6
```

시큐리티를 쓰시는걸로 결정이 되었으면 상관 없는데 단순히 인코더 때문이라면 한번 확인해보세요~

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/common/dto/RequestSignUp.java
> +public class RequestSignUp {
중요한건 아닌데 ErrorResponse와 RequestSignUp을 비교했을 때 Requset,Response가 앞에 오거나 뒤에 오는 형태로 컨벤션이 다른 것 같아요. 혼란을 줄 수 있는 요소 같은데 일관성을 갖추면 좋겠습니다.

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/database/entity/Member.java
> +	private LocalDateTime emailTokenGeneratedAt;
토큰과 관련된 컬럼만 4개정도 되는 것 같네요. 회원 테이블은 이것저것 값을 넣고 활용하기 좋아서 이런식으로 값이 들어가기 시작하면 굉장히 지저분해지기 쉬워요.

가입 시 필요한 토큰 정보는 매번 필요한게 아니기 때문에 가급적이면 회원 테이블에 토큰과 관련된 컬럼을 두지 않는게 어떨까 생각되네요.

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberController.java
> +		}
ErrorResponse를 만드셨던걸로 기억하는데요. 이런 에러가 발생했을 때 동일한 응답을 내려주는게 어떨까요?

요거 `@Valid`를 붙이셨으니 hasErrors로 잡아서 ErrorResponse에 맞게 변형해서 내려주시던가 RestControllerAdvice에서 `MethodArgumentNotValidException` 에러를 잡아서 원하는 응답 형태로 바꿔서 내려주시면 될듯 합니다.

모든 곳에서 hasErrors를 체크해서 내려주긴 번거로우니 RestControllerAdvice를 활용해보세요. 그리고 이건 잘 되는지 테스트도 한번 작성해보시면 좋겠습니다.

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberController.java
> +		memberService.completeSignUp(member);
이런 로직은 컨트롤러에 존재하지 않도록 한번 변경해보세요. 
RestControllerAdvice에서 처리해주도록 설정하신 표준 예외들(IlegalArgumentException 등)을 활용하시면 프레젠테이션 레이어가 지저분해지지 않게 잘 처리할 수 있습니다.

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberService.java
> +	public void sendSignUpEmail(RequestSignUp requestSignUp) {
위에 readOnly 트랜잭션을 쓰도록 하셨는데 save가 발생하고 있어 사용하는 DB나 client에 따라 예외가 발생할 수 있어보여요. 여기는 붙이는게 맞을 것 같습니다.

다만 이런 형태는 좀 좋지 않은게 실수로 붙이는걸 깜빡하면 아예 저장이 안되는 상황이 발생할수도 있어요. 차라리 클래스 레벨에 `@Transactional`을 붙이시고 메소드 레벨에 필요에 따라 `@Transactional(readOnly = true)`를 사용하시는게 맞아보입니다.

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberService.java
> +			String.format("/check-email-token?token=%s&email=%s", member.getEmailToken(), member.getEmail()));
이런 형태로 setter를 활용하시는걸 지양해주세요. 이렇게 setter를 사용하시면 캡슐화에 대한 의미도 없어질뿐더러 이게 어떤 로직을 수행하는건지 같이 협업하는 개발자가 알기 어려워요. 아래처럼 메소드를 활용해주세요.

```suggestion
		SimpleMailMessage mailMessage = new SimpleMailMessage();
		mailMessage.setContent(~~~);
```

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberService.java
> +		}
중복을 체크하는 목적으로 보이는데요. exists를 활용해 boolean 값을 뽑는 형태로 사용하시는게 어떨까요?

2023-02-09 11:21 UTC, f-lab-kyucumber commented on src/main/java/com/flab/todo/member/MemberService.java
> +}
파일의 끝이 개행(new line)으로 끝나게 IDE에 설정을 추가해주세요. 그리 중요한 부분은 아니지만 이런 부분이 불필요한 file change를 만듭니다.

아래 내용도 한번 참고해보세요.
https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

2023-02-09 11:22 UTC, f-lab-kyucumber commented on src/main/resources/application.yaml
> +    password: 'pmoyulxnzyzdeysj'
이거 사용하시는 아이디는 아니죠? 이렇게 노출하시지 말고 로컬 환경이니 환경 변수 등으로 사용하시고 이 값은 제거해주세요.

2023-02-09 11:42 UTC, jaeyeonme commented on src/main/java/com/flab/todo/member/MemberService.java
> +	public void sendSignUpEmail(RequestSignUp requestSignUp) {
그러면 `sendSignUpEmail` 메소드 안에 `validateDuplicateUser(requestSignUp);`, `validatePasswordUser(requestSignUp);` 메소드로 빼주었는데 이런 경우 두 개의 메소드 둘다 `@Transactional(readOnly = true)` 를 쓰는게 맞을까요?

2023-02-09 11:47 UTC, jaeyeonme commented on src/main/java/com/flab/todo/member/MemberService.java
> +	public void sendSignUpEmail(RequestSignUp requestSignUp) {
그러면 `sendSignUpEmail` 메소드 안에 `validateDuplicateUser(requestSignUp);` 와 `validatePasswordUser(requestSignUp);` 두 개의 메소드를 `@Transactional(readOnly = true) 로 해주는 것이 맞을까요?!

2023-02-09 12:40 UTC, jaeyeonme commented on src/main/java/com/flab/todo/database/entity/Member.java
> +	private LocalDateTime emailTokenGeneratedAt;
처음에 @RequestBody 로 회원가입을 하면 random 으로 생성된 인증번호 와 isValid(기본값 False) 도 같이 DB에 저장이 됩니다.
그래서 @RequestParam 으로 DB에 저장된 토큰과 이메일이 일치하면 isValid 도 True로 변하게 하기 위해서 넣은 것인데

그러면 가입 시 토큰은 매번 필요할 것이라고 생각해서 넣었습니다! 그러면 Service layer 로 이동시키는게 맞을까요?!

2023-02-09 13:09 UTC, kyucumber commented on src/main/java/com/flab/todo/member/MemberService.java
> +	public void sendSignUpEmail(RequestSignUp requestSignUp) {
private 메소드에는 Transactional을 붙이지 않으셔도 됩니다. 관련해서 한번 찾아보세요~ 궁금하시면 멘토링 시간에 질문해주셔도 됩니다.

2023-02-09 13:11 UTC, kyucumber commented on src/main/java/com/flab/todo/database/entity/Member.java
> +	private LocalDateTime emailTokenGeneratedAt;
가입시에는  토큰이 매번 필요하겠죠. 그런데 이후에 로그인이나 인증 과정에서 회원 정보를 조회할 때 토큰과 관련된 값은 불필요한 값이 될 것 같습니다.

> 처음에 @requestbody 로 회원가입을 하면 random 으로 생성된 인증번호 와 isValid(기본값 False) 도 같이 DB에 저장이 됩니다. 그래서 @RequestParam 으로 DB에 저장된 토큰과 이메일이 일치하면 isValid 도 True로 변하게 하기 위해서 넣었습니다!

이 내용은 회원 테이블에 해당 데이터들이 있어야 할 이유와는 무관하다고 생각되네요. 요건 멘토링 시간에 질문 드리겠습니다.

2023-02-09 13:27 UTC, jaeyeonme commented on src/main/java/com/flab/todo/member/MemberService.java
> +	public void sendSignUpEmail(RequestSignUp requestSignUp) {
`@Transactional`이 Spring AOP를 사용하여 구현되는데 Proxy 패턴을 사용하여 구현이 되기 때문에 다른 객체가 들어가 있는거군요!

https://velog.io/@ljks789/spring%EC%97%90%EC%84%9C-transactional%EC%97%90-private%EC%9D%B4-%EB%A8%B9%ED%9E%88%EC%A7%80-%EC%95%8A%EB%8A%94-%EC%9D%B4%EC%9C%A0

2023-02-14 14:44 UTC, closed without merging